# Generated by Django 5.2.9 on 2026-06-03 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('target', models.CharField(blank=True, db_index=True, max_length=200)),
                ('source', models.CharField(choices=[('ui', 'UI'), ('api', 'API'), ('cli', 'CLI'), ('system', 'System')], db_index=True, default='system', max_length=10)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit event',
                'verbose_name_plural': 'Audit events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
