# Generated by Django 5.2.9 on 2026-03-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('folder_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=200)),
                ('logo', models.CharField(max_length=200)),
                ('ui_entry_point', models.CharField(max_length=200)),
                ('configuration_entry_point', models.CharField(max_length=200)),
                ('documentation_entry_point', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('lic', models.CharField(max_length=100)),
                ('is_installed', models.BooleanField(default=False)),
            ],
        ),
    ]
