# Generated by Django 5.2.9 on 2026-06-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableapp',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
    ]
